### Vector Autoregression Model  

Vector autoregression (VAR) is used for to capture the relationship among multiple features including 'CRASH_DT','K_PEOPLE', 'PERSONS_INJURED', 'PEDESTRIANS_KILLED',and'PEDESTRIANS_INJURED.'

In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import datetime
import matplotlib.pyplot as plt


In [ ]:
data = pd.read_csv("full_crash1.csv")

In [ ]:
#jack
data['CRASH_YEAR'].value_counts()


2018    131848
2016    128525
2019    128172
2017    127375
2015    125800
2014    120282
2020    105600
2021     61836
Name: CRASH_YEAR, dtype: int64

In [ ]:
data = data[data['CRASH_YEAR'] < 2020]

In [ ]:
data['CRASH_YEAR'].value_counts()


2018    131848
2016    128525
2019    128172
2017    127375
2015    125800
2014    120282
Name: CRASH_YEAR, dtype: int64

In [ ]:
data['PLAN_DISTRICT'].value_counts()

Northern Virginia                          178363
Hampton Roads                              153863
Richmond Regional                           88583
George Washington Regional                  37987
Richmond Regional, Crater                   34065
Central Shenandoah                          29688
Roanoke Valley-Alleghany                    27282
Thomas Jefferson                            24205
Region 2000                                 22489
Northern Shenandoah Valley                  21549
Mount Rogers                                20535
Rappahannock - Rapidan                      19259
Crater                                      18096
New River Valley                            16927
West Piedmont                               16108
Cumberland Plateau                           8661
Commonwealth Regional                        8045
Southside                                    7988
Lenowisco                                    7573
Roanoke Valley-Alleghany, West Piedmont      5484


Northern Virginia                       
Hampton Roads                           
George Washington Regional             
Central Shenandoah                         
Roanoke Valley-Alleghany                   
Thomas Jefferson                         
Region 2000                                 
Northern Shenandoah Valley
Rappahannock - Rapidan

In [ ]:
data1 = data[data['PLAN_DISTRICT'] == 'Northern Virginia']
data2 = data[data['PLAN_DISTRICT'] == 'Hampton Roads']
data3 = data[data['PLAN_DISTRICT'] == 'George Washington Regional']
data4 = data[data['PLAN_DISTRICT'] == 'Central Shenandoah']
data5 = data[data['PLAN_DISTRICT'] == 'Roanoke Valley-Alleghany']
data6 = data[data['PLAN_DISTRICT'] == 'Thomas Jefferson']
data7 = data[data['PLAN_DISTRICT'] == 'Region 2000']
data8 = data[data['PLAN_DISTRICT'] == 'Northern Shenandoah Valley']
data9 = data[data['PLAN_DISTRICT'] == 'Rappahannock - Rapidan']


In [ ]:
data1.columns

Index(['X', 'Y', 'OBJECTID', 'DOCUMENT_NBR', 'CRASH_YEAR', 'CRASH_DT',
       'CRASH_MILITARY_TM', 'CRASH_SEVERITY', 'K_PEOPLE', 'A_PEOPLE',
       'B_PEOPLE', 'C_PEOPLE', 'PERSONS_INJURED', 'PEDESTRIANS_KILLED',
       'PEDESTRIANS_INJURED', 'VEH_COUNT', 'COLLISION_TYPE',
       'WEATHER_CONDITION', 'LIGHT_CONDITION', 'RD_TYPE',
       'ROADWAY_SURFACE_COND', 'RELATION_TO_ROADWAY', 'ROADWAY_ALIGNMENT',
       'ROADWAY_SURFACE_TYPE', 'ROADWAY_DEFECT', 'ROADWAY_DESCRIPTION',
       'INTERSECTION_TYPE', 'TRAFFIC_CONTROL_TYPE', 'TRFC_CTRL_STATUS_TYPE',
       'WORK_ZONE_RELATED', 'WORK_ZONE_LOCATION', 'WORK_ZONE_TYPE',
       'FIRST_HARMFUL_EVENT', 'FIRST_HARMFUL_EVENT_LOC', 'ALCOHOL_NOTALCOHOL',
       'BELTED_UNBELTED', 'BIKE_NONBIKE', 'DISTRACTED_NOTDISTRACTED',
       'DROWSY_NOTDROWSY', 'DRUG_NODRUG', 'GR_NOGR', 'HITRUN_NOT_HITRUN',
       'LGTRUCK_NONLGTRUCK', 'MOTOR_NONMOTOR', 'PED_NONPED', 'SPEED_NOTSPEED',
       'SCHOOL_ZONE', 'SENIOR_NOTSENIOR', 'YOUNG_NOTYOUNG', 'MAINLINE_YN',

In [ ]:
data1['VDOT_DISTRICT'].value_counts()

9. Northern Virginia    178363
Name: VDOT_DISTRICT, dtype: int64

In [ ]:
#Chris dont touch my cells

In [ ]:
#Forecast - the number of crashes for follwing year 2014-2019
#change data column into month

In [ ]:
data1.head()

X          Y  OBJECTID  ...  OFFSET  ANIMAL SPEED_DIFF_MAX
2  -77.220990  38.762770         3  ...     0.0      No            NaN
4  -77.306306  38.847087         5  ...    53.0      No            NaN
12 -77.670294  38.883672        13  ...    95.0      No            NaN
19 -77.300515  38.850329        20  ...   359.0      No            NaN
20 -77.068308  38.855431        21  ...   829.0      No            NaN

[5 rows x 69 columns]

In [ ]:
isinstance(data1["CRASH_DT"],str)

False

In [ ]:
def change_date(date):
    month = date[5: 7]
    year = date[0: 4]
    full_date =  year + '-' + month
    return full_date


In [ ]:
def to_time_it(x):
    return pd.to_datetime(x, format='%Y-%m', errors='ignore')

In [ ]:
#change_date(data1.loc[0,"CRASH_DT"])  

In [ ]:
data1['CRASH_DT'] = data1['CRASH_DT'].map(lambda x: change_date(x))
data1['CRASH_DT'] = data1['CRASH_DT'].map(lambda x: to_time_it(x))

data2['CRASH_DT'] = data2['CRASH_DT'].map(lambda x: change_date(x))
data2['CRASH_DT'] = data2['CRASH_DT'].map(lambda x: to_time_it(x))

data3['CRASH_DT'] = data3['CRASH_DT'].map(lambda x: change_date(x))
data3['CRASH_DT'] = data3['CRASH_DT'].map(lambda x: to_time_it(x))

data4['CRASH_DT'] = data4['CRASH_DT'].map(lambda x: change_date(x))
data4['CRASH_DT'] = data4['CRASH_DT'].map(lambda x: to_time_it(x))

data5['CRASH_DT'] = data5['CRASH_DT'].map(lambda x: change_date(x))
data5['CRASH_DT'] = data5['CRASH_DT'].map(lambda x: to_time_it(x))

data6['CRASH_DT'] = data6['CRASH_DT'].map(lambda x: change_date(x))
data6['CRASH_DT'] = data6['CRASH_DT'].map(lambda x: to_time_it(x))

data7['CRASH_DT'] = data7['CRASH_DT'].map(lambda x: change_date(x))
data7['CRASH_DT'] = data7['CRASH_DT'].map(lambda x: to_time_it(x))

data8['CRASH_DT'] = data8['CRASH_DT'].map(lambda x: change_date(x))
data8['CRASH_DT'] = data8['CRASH_DT'].map(lambda x: to_time_it(x))

data9['CRASH_DT'] = data9['CRASH_DT'].map(lambda x: change_date(x))
data9['CRASH_DT'] = data9['CRASH_DT'].map(lambda x: to_time_it(x))

data1.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documen

X          Y  OBJECTID  ...  OFFSET  ANIMAL SPEED_DIFF_MAX
2  -77.220990  38.762770         3  ...     0.0      No            NaN
4  -77.306306  38.847087         5  ...    53.0      No            NaN
12 -77.670294  38.883672        13  ...    95.0      No            NaN
19 -77.300515  38.850329        20  ...   359.0      No            NaN
20 -77.068308  38.855431        21  ...   829.0      No            NaN

[5 rows x 69 columns]

In [ ]:
data1['WORK_ZONE_LOCATION'].value_counts()

3. Activity Area           5216
1. Advance Warning Area    1086
2. Transition Area          772
4. Termination Area         316
Name: WORK_ZONE_LOCATION, dtype: int64

In [ ]:
#data1.set_index('RTE_NM', inplace=True)

In [ ]:
#data1.head()

In [ ]:
#, Suspected Serious Injury (A), 
#Suspected Minor Injury (B), Possible Injury (C), and No Apparent Injury (O)

In [ ]:
data1 = data1[['CRASH_DT','K_PEOPLE', 'PERSONS_INJURED', 'PEDESTRIANS_KILLED',
       'PEDESTRIANS_INJURED']]
data2 = data2[['CRASH_DT','K_PEOPLE', 'PERSONS_INJURED', 'PEDESTRIANS_KILLED',
       'PEDESTRIANS_INJURED']]
data3 = data3[['CRASH_DT','K_PEOPLE', 'PERSONS_INJURED', 'PEDESTRIANS_KILLED',
       'PEDESTRIANS_INJURED']]
data4 = data4[['CRASH_DT','K_PEOPLE', 'PERSONS_INJURED', 'PEDESTRIANS_KILLED',
       'PEDESTRIANS_INJURED']]
data5 = data5[['CRASH_DT','K_PEOPLE', 'PERSONS_INJURED', 'PEDESTRIANS_KILLED',
       'PEDESTRIANS_INJURED']]
data6 = data6[['CRASH_DT','K_PEOPLE', 'PERSONS_INJURED', 'PEDESTRIANS_KILLED',
       'PEDESTRIANS_INJURED']]
data7 = data7[['CRASH_DT','K_PEOPLE', 'PERSONS_INJURED', 'PEDESTRIANS_KILLED',
       'PEDESTRIANS_INJURED']]
data8 = data8[['CRASH_DT','K_PEOPLE', 'PERSONS_INJURED', 'PEDESTRIANS_KILLED',
       'PEDESTRIANS_INJURED']]     
data9 = data9[['CRASH_DT','K_PEOPLE', 'PERSONS_INJURED', 'PEDESTRIANS_KILLED',
       'PEDESTRIANS_INJURED']]              

In [ ]:
grouped1 = data1.groupby(by = ["CRASH_DT"]).sum()
grouped2 = data2.groupby(by = ["CRASH_DT"]).sum()
grouped3 = data3.groupby(by = ["CRASH_DT"]).sum()
grouped4 = data4.groupby(by = ["CRASH_DT"]).sum()
grouped5 = data5.groupby(by = ["CRASH_DT"]).sum()
grouped6 = data6.groupby(by = ["CRASH_DT"]).sum()
grouped7 = data7.groupby(by = ["CRASH_DT"]).sum()
grouped8 = data8.groupby(by = ["CRASH_DT"]).sum()
grouped9 = data9.groupby(by = ["CRASH_DT"]).sum()

In [ ]:

#crashed_dt = grouped.sum()
#CRASH_DT.loc[rows, columns]

In [ ]:
grouped1.head()

K_PEOPLE  PERSONS_INJURED  PEDESTRIANS_KILLED  PEDESTRIANS_INJURED
CRASH_DT                                                                      
2014-01-01         7             1135                   1                   51
2014-02-01         9             1000                   3                   32
2014-03-01         7             1166                   3                   22
2014-04-01         3             1271                   0                   44
2014-05-01        12             1514                   2                   47

In [ ]:
#check if stationary

In [ ]:
grouped1.dtypes


K_PEOPLE               int64
PERSONS_INJURED        int64
PEDESTRIANS_KILLED     int64
PEDESTRIANS_INJURED    int64
dtype: object

In [ ]:
#checking stationary

In [ ]:
from statsmodels.tsa.vector_ar.vecm import coint_johansen


In [ ]:
coint_johansen(grouped1,-1,1).eig
coint_johansen(grouped2,-1,1).eig
coint_johansen(grouped3,-1,1).eig
coint_johansen(grouped4,-1,1).eig
coint_johansen(grouped5,-1,1).eig
coint_johansen(grouped6,-1,1).eig
coint_johansen(grouped7,-1,1).eig
coint_johansen(grouped8,-1,1).eig
coint_johansen(grouped9,-1,1).eig


array([0.44943551, 0.26472482, 0.23459534, 0.00284976])

In [ ]:
#creating a train & validation set

In [ ]:
train1 = grouped1[:int(0.8*(len(grouped1)))]
valid1 = grouped1[int(0.8*(len(grouped1))):]

train2 = grouped2[:int(0.8*(len(grouped2)))]
valid2 = grouped2[int(0.8*(len(grouped2))):]

train3 = grouped3[:int(0.8*(len(grouped3)))]
valid3 = grouped3[int(0.8*(len(grouped3))):]

train4 = grouped4[:int(0.8*(len(grouped4)))]
valid4 = grouped4[int(0.8*(len(grouped4))):]

train5 = grouped5[:int(0.8*(len(grouped5)))]
valid5 = grouped5[int(0.8*(len(grouped5))):]

train6 = grouped6[:int(0.8*(len(grouped6)))]
valid6 = grouped6[int(0.8*(len(grouped6))):]

train7 = grouped7[:int(0.8*(len(grouped7)))]
valid7 = grouped7[int(0.8*(len(grouped7))):]

train8 = grouped8[:int(0.8*(len(grouped8)))]
valid8 = grouped8[int(0.8*(len(grouped8))):]

train9 = grouped9[:int(0.8*(len(grouped9)))]
valid9 = grouped9[int(0.8*(len(grouped9))):]

In [ ]:
from statsmodels.tsa.vector_ar.var_model import VAR


In [ ]:
model1 = VAR(endog=train1)
model_fit1 = model1.fit()

model2 = VAR(endog=train2)
model_fit2 = model2.fit()

model3 = VAR(endog=train3)
model_fit3 = model3.fit()

model4 = VAR(endog=train4)
model_fit4 = model4.fit()

model5 = VAR(endog=train5)
model_fit5 = model5.fit()

model6 = VAR(endog=train6)
model_fit6 = model6.fit()

model7 = VAR(endog=train7)
model_fit7 = model7.fit()

model8 = VAR(endog=train8)
model_fit8 = model8.fit()

model9 = VAR(endog=train9)
model_fit9 = model9.fit()




/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/base/tsa_model.py:165: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  % freq, ValueWarning)
/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/base/tsa_model.py:165: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  % freq, ValueWarning)
/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/base/tsa_model.py:165: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  % freq, ValueWarning)
/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/base/tsa_model.py:165: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  % freq, ValueWarning)
/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/base/tsa_model.py:165: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  % freq, ValueWarning)
/usr/local/lib/python3.7/dist-

In [ ]:
prediction1 = model_fit1.forecast(model_fit1.y, steps=len(valid1))

prediction2 = model_fit2.forecast(model_fit2.y, steps=len(valid2))

prediction3 = model_fit3.forecast(model_fit3.y, steps=len(valid3))

prediction4 = model_fit4.forecast(model_fit4.y, steps=len(valid4))

prediction5 = model_fit5.forecast(model_fit5.y, steps=len(valid5))

prediction6 = model_fit6.forecast(model_fit6.y, steps=len(valid6))

prediction7 = model_fit7.forecast(model_fit7.y, steps=len(valid7))

prediction8 = model_fit8.forecast(model_fit8.y, steps=len(valid8))

prediction9 = model_fit9.forecast(model_fit9.y, steps=len(valid9))



/usr/local/lib/python3.7/dist-packages/statsmodels/base/wrapper.py:35: FutureWarning: y is a deprecated alias for endog, will be removed in version 0.11.0
  obj = getattr(results, attr)


In [ ]:
from math import sqrt
from sklearn.metrics import mean_squared_error


In [ ]:
cols = grouped2.columns

pred2 = pd.DataFrame(index=range(0,len(prediction2)),columns=[cols])
for j in range(0,4):
    for i in range(0, len(prediction2)):
        pred2.iloc[i][j] = prediction2[i][j]

#check rmse
#for i in cols:
    #print('rmse value for', i, 'is : ', sqrt(mean_squared_error(pred2[i], valid2[i])))

TypeError: ignored

In [ ]:
cols = grouped2.columns

pred2 = pd.DataFrame(index=range(0,len(prediction2)),columns=[cols])
for j in range(0,4):
    for i in range(0, len(prediction2)):
        pred2.iloc[i][j] = prediction2[i][j]

#check rmse
for i in cols:
    print('rmse value for', i, 'is : ', sqrt(mean_squared_error(pred2[i], valid2[i])))

In [ ]:
pred3 = pd.DataFrame(index=range(0,len(prediction3)),columns=[cols])
for j in range(0,4):
    for i in range(0, len(prediction3)):
        pred3.iloc[i][j] = prediction3[i][j]

#check rmse
for i in cols:
    print('rmse value for', i, 'is : ', sqrt(mean_squared_error(pred3[i], valid3[i])))

In [ ]:
pred4 = pd.DataFrame(index=range(0,len(prediction4)),columns=[cols])
for j in range(0,4):
    for i in range(0, len(prediction4)):
        pred4.iloc[i][j] = prediction4[i][j]

#check rmse
for i in cols:
    print('rmse value for', i, 'is : ', sqrt(mean_squared_error(pred4[i], valid4[i])))

In [ ]:
pred5 = pd.DataFrame(index=range(0,len(prediction5)),columns=[cols])
for j in range(0,4):
    for i in range(0, len(prediction5)):
        pred5.iloc[i][j] = prediction5[i][j]

#check rmse
for i in cols:
    print('rmse value for', i, 'is : ', sqrt(mean_squared_error(pred5[i], valid5[i])))

In [ ]:
pred6 = pd.DataFrame(index=range(0,len(prediction6)),columns=[cols])
for j in range(0,4):
    for i in range(0, len(prediction6)):
        pred6.iloc[i][j] = prediction6[i][j]

#check rmse
for i in cols:
    print('rmse value for', i, 'is : ', sqrt(mean_squared_error(pred6[i], valid6[i])))

In [ ]:
pred7 = pd.DataFrame(index=range(0,len(prediction7)),columns=[cols])
for j in range(0,4):
    for i in range(0, len(prediction7)):
        pred7.iloc[i][j] = prediction7[i][j]

#check rmse
for i in cols:
    print('rmse value for', i, 'is : ', sqrt(mean_squared_error(pred7[i], valid7[i])))

In [ ]:
pred8 = pd.DataFrame(index=range(0,len(prediction8)),columns=[cols])
for j in range(0,4):
    for i in range(0, len(prediction8)):
        pred8.iloc[i][j] = prediction8[i][j]

#check rmse
for i in cols:
    print('rmse value for', i, 'is : ', sqrt(mean_squared_error(pred8[i], valid8[i])))

In [ ]:
pred9 = pd.DataFrame(index=range(0,len(prediction9)),columns=[cols])
for j in range(0,4):
    for i in range(0, len(prediction9)):
        pred9.iloc[i][j] = prediction9[i][j]

#check rmse
for i in cols:
    print('rmse value for', i, 'is : ', sqrt(mean_squared_error(pred9[i], valid9[i])))

TypeError: ignored

In [ ]:
model1 = VAR(endog=grouped1)
model_fit1 = model1.fit()
yhat1 = model_fit1.forecast(model_fit1.y, steps=3)
print(yhat1)


[[   6.55688057 1161.71784396    1.88847862   47.09157241]
 [   6.94786922 1177.7363701     1.98894097   43.80660811]
 [   6.92371095 1198.28049907    2.04270357   43.46832612]]


/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/base/tsa_model.py:165: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  % freq, ValueWarning)
/usr/local/lib/python3.7/dist-packages/statsmodels/base/wrapper.py:35: FutureWarning: y is a deprecated alias for endog, will be removed in version 0.11.0
  obj = getattr(results, attr)


In [ ]:
model2 = VAR(endog=grouped2)
model_fit2 = model2.fit()
yhat2 = model_fit2.forecast(model_fit2.y, steps=3)
print(yhat2)

[[  11.20178154 1335.03423327    2.673097     34.16529353]
 [  11.05323435 1318.65422255    2.15893601   33.54669434]
 [  10.91941926 1316.63198468    2.06035991   33.09097177]]


/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/base/tsa_model.py:165: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  % freq, ValueWarning)
/usr/local/lib/python3.7/dist-packages/statsmodels/base/wrapper.py:35: FutureWarning: y is a deprecated alias for endog, will be removed in version 0.11.0
  obj = getattr(results, attr)


In [ ]:
model3 = VAR(endog=grouped3)
model_fit3 = model3.fit()
yhat3 = model_fit3.forecast(model_fit3.y, steps=3)
print(yhat3)

[[  2.84772957 239.67389904   0.3169487    3.61059011]
 [  3.04865125 248.9548571    0.31074938   3.76232727]
 [  3.23720672 252.33914526   0.36080871   3.73461635]]


/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/base/tsa_model.py:165: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  % freq, ValueWarning)
/usr/local/lib/python3.7/dist-packages/statsmodels/base/wrapper.py:35: FutureWarning: y is a deprecated alias for endog, will be removed in version 0.11.0
  obj = getattr(results, attr)


In [ ]:
model4 = VAR(endog=grouped4)
model_fit4 = model4.fit()
yhat4 = model_fit4.forecast(model_fit4.y, steps=3)
print(yhat4)

[[3.29762137e+00 1.91142651e+02 1.87525335e-01 3.25811627e+00]
 [3.22984322e+00 1.93720447e+02 2.51057601e-01 3.31833453e+00]
 [3.21026530e+00 1.93853383e+02 2.54653981e-01 3.31955726e+00]]


/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/base/tsa_model.py:165: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  % freq, ValueWarning)
/usr/local/lib/python3.7/dist-packages/statsmodels/base/wrapper.py:35: FutureWarning: y is a deprecated alias for endog, will be removed in version 0.11.0
  obj = getattr(results, attr)


In [ ]:
model5 = VAR(endog=grouped5)
model_fit5 = model5.fit()
yhat5 = model_fit5.forecast(model_fit5.y, steps=3)
print(yhat5)

[[  2.20838037 152.52192017   0.33467409   3.75072405]
 [  2.07371993 150.19463991   0.33811242   3.9878071 ]
 [  2.08369754 149.43063616   0.33798715   3.97450014]]


/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/base/tsa_model.py:165: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  % freq, ValueWarning)
/usr/local/lib/python3.7/dist-packages/statsmodels/base/wrapper.py:35: FutureWarning: y is a deprecated alias for endog, will be removed in version 0.11.0
  obj = getattr(results, attr)


In [ ]:
model6 = VAR(endog=grouped6)
model_fit6 = model6.fit()
yhat6 = model_fit6.forecast(model_fit6.y, steps=3)
print(yhat6)

[[  2.75689045 174.92677636   0.44912207   3.10024264]
 [  2.65331414 164.20673257   0.32346577   3.49161289]
 [  2.64970069 158.64245975   0.28750422   3.61851177]]


/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/base/tsa_model.py:165: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  % freq, ValueWarning)
/usr/local/lib/python3.7/dist-packages/statsmodels/base/wrapper.py:35: FutureWarning: y is a deprecated alias for endog, will be removed in version 0.11.0
  obj = getattr(results, attr)


In [ ]:
model7 = VAR(endog=grouped7)
model_fit7 = model7.fit()
yhat7 = model_fit7.forecast(model_fit7.y, steps=3)
print(yhat7)

[[2.62329554e+00 1.52496425e+02 2.43615469e-01 2.58834839e+00]
 [2.69973312e+00 1.57025363e+02 1.41172185e-01 2.38875263e+00]
 [2.71166664e+00 1.59969781e+02 1.36512220e-01 2.34138595e+00]]


/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/base/tsa_model.py:165: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  % freq, ValueWarning)
/usr/local/lib/python3.7/dist-packages/statsmodels/base/wrapper.py:35: FutureWarning: y is a deprecated alias for endog, will be removed in version 0.11.0
  obj = getattr(results, attr)


In [ ]:
model8 = VAR(endog=grouped8)
model_fit8 = model8.fit()
yhat8 = model_fit8.forecast(model_fit8.y, steps=3)
print(yhat8)

[[  2.08813772 112.04943016   0.21755312   2.05124727]
 [  2.70763782 120.62951962   0.27684798   2.38246851]
 [  2.68513532 122.93661527   0.25546188   2.54796417]]


/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/base/tsa_model.py:165: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  % freq, ValueWarning)
/usr/local/lib/python3.7/dist-packages/statsmodels/base/wrapper.py:35: FutureWarning: y is a deprecated alias for endog, will be removed in version 0.11.0
  obj = getattr(results, attr)


In [ ]:
model9 = VAR(endog=grouped9)
model_fit9 = model9.fit()
yhat9 = model_fit9.forecast(model_fit9.y, steps=3)
print(yhat9)

[[  2.80793722 150.49071112   0.17103873   1.24095038]
 [  2.60775357 150.80993692   0.18042047   1.31084516]
 [  2.62134868 150.0149849    0.19056387   1.28910233]]


/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/base/tsa_model.py:165: ValueWarning: No frequency information was provided, so inferred frequency MS will be used.
  % freq, ValueWarning)
/usr/local/lib/python3.7/dist-packages/statsmodels/base/wrapper.py:35: FutureWarning: y is a deprecated alias for endog, will be removed in version 0.11.0
  obj = getattr(results, attr)


In [ ]:
grouped9.head()

K_PEOPLE  PERSONS_INJURED  PEDESTRIANS_KILLED  PEDESTRIANS_INJURED
CRASH_DT                                                                      
2014-01-01         3              128                   0                    2
2014-02-01         0              115                   0                    2
2014-03-01         3              112                   0                    3
2014-04-01         3              149                   0                    2
2014-05-01         2              178                   0                    2